
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package uk.ac.ucl.jsh.core.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ATOMEND = 6;
  public static final int PIPE = 3;
  public static final int LESSER = 8;
  public static final int SQUOTE = 9;
  public static final int SEMI = 2;
  public static final int GREATER = 7;
  public static final int DQUOTE = 10;
  public static final int EOF = 0;
  public static final int ATOM = 5;
  public static final int error = 1;
  public static final int BACKQUOTE = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PIPE",
  "BACKQUOTE",
  "ATOM",
  "ATOMEND",
  "GREATER",
  "LESSER",
  "SQUOTE",
  "DQUOTE"
  };
}

